### ISSUE TITLE
"ipython: command not found"

### ISSUE THREAD

**Issue by camillelarousse** [lewagon/data-kit#31]
Hi,

I followed all the steps of the installation process. Now that I just want to test if it works, running this :
![Screenshot 2019-04-17 at 11 45 34](https://user-images.githubusercontent.com/48549666/56278466-93ddde80-6106-11e9-99c6-b120c9b1e56c.png)

I have the following result: "ipython: command not found". I'm kind of a total newbie and would appreciate very much if someone could help me so that I can do the training I'm supposed to do.

Thanks!

**Comment by manuebourgain** [comment]
Hi Camille, i got the same issue, install anaconda instead of canopy, it worked fine for me
